[project]
name = "new-icr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "matplotlib>=3.10.5",
    "scipy>=1.16.1",
    "torch>=2.8.0",
    "torchopt>=0.7.3",
    "tqdm>=4.67.1",
    "transformers>=4.55.4",
]
